# syntax=docker/dockerfile:labs
FROM node:24-slim

RUN npm install -g npm@11.14.1

WORKDIR /app

#{ copy_packages }#
RUN --mount=type=cache,target=/root/.npm npm ci --omit=dev
#{ copy_src }#

WORKDIR /app/recipes/service/monolith
CMD ["npm", "start"]
