export const recipe_form = {
  title_label: "Title",
  title_placeholder: "Recipe title",
  subtitle_label: "Subtitle",
  subtitle_placeholder: "Brief subtitle for menus and lists",
  description_label: "Description (optional)",
  description_placeholder: "Longer description for recipe detail",
  is_public_label: "Public",
  is_public_hint: "Visible to everyone when checked",
  ingredients_label: "Ingredients",
  instructions_label: "Instructions (markdown)",
  instructions_placeholder: "1. Preheat oven...\n2. Mix ingredients...",
  note_label: "Note (attached to this version when you save)",
  note_placeholder: "How it went, what to try next…",
  tab_metadata: "Metadata",
  tab_contents: "Contents",
  submit_create: "Create recipe",
  submit_update_latest: "Update latest version",
  submit_save_new_version: "Save as new version",
};
