export const recipes_edit_page = {
  title: "Edit recipe",
  back_to_list: "Back to recipes",
  preview_heading: "Preview",
  breadcrumb_home: "Home",
  breadcrumb_recipes: "Recipes",
  breadcrumb_edit: "Edit",
  commit_dialog_title: "Save as new version",
  commit_message_label: "Commit message",
  commit_message_placeholder: "Describe what changed…",
  commit_default_prefix: "update ",
  commit_confirm: "Save",
  commit_cancel: "Cancel",
  save_button: "Save",
  save_menu_update_current: "Update current version",
  save_menu_create_new: "Create new version",
};
