/**
 * Environment variables for the `@sderickson/hub-monolith` package, including inherited variables.
 * Generated by `@saflib/env`. To update, make changes to the adjacent `env.schema.json`, navigate to the package root, and run `npm exec saf-env generate`.
 */

export interface HubMonolithEnvSchema {
  /**
   * Comma-separated list of admin emails
   */
  ADMIN_EMAILS: string;
  /**
   * Whether to allow the creation of new databases. Useful for ensuring existing production environments don't inadvertently create new databases.
   */
  ALLOW_DB_CREATION?: "true" | "false";
  /**
   * The Azure Blob Storage URL.
   */
  AZURE_COLD_BLOB_STORAGE_URL?: string;
  /**
   * The Azure Blob Storage URL.
   */
  AZURE_COOL_BLOB_STORAGE_URL?: string;
  /**
   * The Azure Blob Storage URL.
   */
  AZURE_HOT_BLOB_STORAGE_URL?: string;
  /**
   * Comma-separated list of client subdomains, e.g. 'www,app,auth,'. Include an empty string (such as in the example) to indicate there's a client for the root domain.
   */
  CLIENT_SUBDOMAINS: string;
  /**
   * The name of the deployment, e.g. 'production', 'staging', 'development'. This may be used in strings such as database file names and logging metadata; each deployment should have a unique name.
   */
  DEPLOYMENT_NAME: string;
  /**
   * The root domain of the deployment, e.g. 'saf.com'.
   */
  DOMAIN: string;
  /**
   * Comma-separated list of domains to redirect to the root domain, e.g. 'old-subdomain1.saf.com,old-subdomain2.saf.com'.
   */
  DOMAIN_REDIRECTS?: string;
  HUB_SERVICE_HTTP_HOST: string;
  /**
   * Infisical environment slug (e.g. dev, staging, prod). Required for live API calls (e.g. getSecret); not needed when using the mock client.
   */
  INFISICAL_ENVIRONMENT?: string;
  /**
   * Infisical project ID. Required for live API calls (e.g. getSecret); not needed when using the mock client.
   */
  INFISICAL_PROJECT_ID?: string;
  /**
   * Infisical token for authenticating with the Infisical API (e.g. a project or universal auth token). Required for live secret fetches; omit or set to 'mock' to use the mock client (e.g. in tests or when the integration is disabled).
   */
  INFISICAL_TOKEN?: string;
  /**
   * Host URL for the Ory Kratos courier callback server (e.g. recipes-monolith:3000).
   */
  KRATOS_COURIER_HTTP_HOST: string;
  /**
   * The hostname or URL of the Loki instance to send logs to (e.g., http://loki:3100)
   */
  LOKI_HOSTNAME?: string;
  /**
   * The port number of the Loki instance to send logs to (e.g., 3100)
   */
  LOKI_PORT?: string;
  /**
   * Whether to mock 3rd party integrations. Set to 'true' to mock. And integration packages should respect this setting.
   */
  MOCK_INTEGRATIONS?: "true" | "false";
  /**
   * The environment of the deployment. Generally should avoid using this, consider its use deprecated, prefer instead more specific environment variables.
   */
  NODE_ENV: "development" | "production" | "test";
  NOTEBOOK_SERVICE_HTTP_HOST: string;
  /**
   * The protocol of the deployment, e.g. 'https'
   */
  PROTOCOL: "https" | "http";
  RECIPES_SERVICE_HTTP_HOST: string;
  SENTRY_DSN?: string;
  /**
   * Comma-separated list of service subdomains, e.g. 'revenue,geo,identity,core'.
   */
  SERVICE_SUBDOMAINS: string;
  /**
   * The trademark of the product provided at the domain, e.g. 'Hooli Chat'.
   */
  TRADEMARK?: string;
  /**
   * The timezone of the deployment, e.g. 'America/New_York'. Must be UTC.
   */
  TZ: "UTC";
  /**
   * Unsplash API Access Key. Create an application at https://unsplash.com/developers to obtain an access key. Required for live API calls; omit or set to 'mock' to use the mock client (e.g. in tests or when the integration is disabled).
   */
  UNSPLASH_API_KEY?: string;
}

/**
 * `process.env` casted to the `HubMonolithEnvSchema` type.
 */
export const typedEnv = (globalThis.process
  ? process.env
  : {}) as unknown as HubMonolithEnvSchema;
