export const members_management_dialog = {
  title: "Members",
  add_member: "Add member",
  email_label: "Email",
  email_placeholder: "email\\@example.com",
  role_label: "Role",
  role_creator: "Creator",
  change_role: "Change role",
  remove_member: "Remove",
  done: "Done",
  no_members: "No members.",
  role_owner: "Owner",
  role_editor: "Editor",
  role_viewer: "Viewer",
  actions_column: "Actions",
};
