services:
  caddy:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: caddy
    volumes: !override []
    env_file: !override
      - ./env.caddy.prod-local

  # BEGIN WORKFLOW AREA monolith FOR product/init
  monolith:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: monolith
    volumes: !override []
    env_file: !override
      - ./env.monolith.prod-local

  # END WORKFLOW AREA

  loki:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: loki
    volumes:
      - ./remote-assets/loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml

  prometheus:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: prometheus
    volumes:
      - ./remote-assets/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: grafana
    volumes: !override []

  kratos-migrate:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: kratos-migrate
    volumes: !override
      - ./kratos-prod-local/data:/var/lib/sqlite
      - ./kratos-prod-local:/etc/config/kratos

  kratos:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes: !override
      - ./kratos-prod-local/data:/var/lib/sqlite
      - ./kratos-prod-local:/etc/config/kratos

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    command: "azurite-blob --blobHost 0.0.0.0 --loose"

volumes:
  caddy_data:
  caddy_config:
