#!/usr/bin/env bash
# Writes GIT_HASH_ROOT and GIT_HASH_SAFLIB (with -dirty when uncommitted) to .env.git-hashes.
# Run from recipes/dev so the file is written there. Used by docker-compose env_file.

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# scripts is recipes/dev/scripts, so repo root is recipes/dev/../..
DEV_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$DEV_DIR/../.." && pwd)"
OUT_FILE="$DEV_DIR/.env.git-hashes"

cd "$REPO_ROOT"
ROOT_HASH="$(git rev-parse HEAD)"
if [ -n "$(git status --porcelain)" ]; then
  ROOT_HASH="${ROOT_HASH}-dirty"
fi

SAFLIB_HASH="unknown"
if [ -d "saflib" ]; then
  SAFLIB_HASH="$(git -C saflib rev-parse HEAD 2>/dev/null)" || true
  if [ -n "$SAFLIB_HASH" ]; then
    if [ -n "$(git -C saflib status --porcelain 2>/dev/null)" ]; then
      SAFLIB_HASH="${SAFLIB_HASH}-dirty"
    fi
  else
    SAFLIB_HASH="unknown"
  fi
fi

cat > "$OUT_FILE" << EOF
# Generated by scripts/git-hashes.sh — do not edit
GIT_HASH_ROOT=$ROOT_HASH
GIT_HASH_SAFLIB=$SAFLIB_HASH
VITE_GIT_HASH_ROOT=$ROOT_HASH
VITE_GIT_HASH_SAFLIB=$SAFLIB_HASH
EOF
echo "Wrote $OUT_FILE (root=$ROOT_HASH saflib=$SAFLIB_HASH)"

# Export so "source scripts/git-hashes.sh" gives docker-compose substitution the values
export GIT_HASH_ROOT="$ROOT_HASH"
export GIT_HASH_SAFLIB="$SAFLIB_HASH"
