#!/usr/bin/env bash
# Writes dev-site.env for the recipes product checkout (saflib as submodule).
set -euo pipefail

DEV_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PRODUCT_ROOT_DIR="$(cd "$DEV_DIR/../.." && pwd)"
SAFLIB_ROOT="$PRODUCT_ROOT_DIR/saflib"
OUT="$DEV_DIR/dev-site.env"

PRODUCT_ROOT="recipes"
REPO_MOUNT="$PRODUCT_ROOT_DIR"

cat > "$OUT" <<EOF
# Generated by scripts/resolve-dev-site-env.sh — do not commit
DEV_SITE_REPO_MOUNT=$REPO_MOUNT
DEV_SITE_PRODUCT_ROOT=$PRODUCT_ROOT
EOF

if [[ -f "$SAFLIB_ROOT/.git" ]] && grep -q '^gitdir:' "$SAFLIB_ROOT/.git" 2>/dev/null; then
  GIT_DIR_MOUNT="$PRODUCT_ROOT_DIR/.git/modules/saflib"
  if [[ -d "$GIT_DIR_MOUNT" ]]; then
    cat >> "$OUT" <<EOF
DEV_SITE_GIT_DIR_MOUNT=$GIT_DIR_MOUNT
EOF
    echo "dev-site: repo=$REPO_MOUNT (saflib submodule) product=$PRODUCT_ROOT git-dir=$GIT_DIR_MOUNT" >&2
  else
    echo "dev-site: repo=$REPO_MOUNT product=$PRODUCT_ROOT (submodule git dir missing at $GIT_DIR_MOUNT)" >&2
  fi
else
  echo "dev-site: repo=$REPO_MOUNT product=$PRODUCT_ROOT" >&2
fi
