export const recipes_detail_page = {
  title: "Recipe",
  short_description: "Summary",
  long_description: "Description",
  ingredients: "Ingredients",
  instructions: "Instructions",
  breadcrumb_home: "Home",
  breadcrumb_collections: "Collections",
  breadcrumb_recipes: "Recipes",
  back_to_list: "Back to recipes",
  edit_recipe: "Edit recipe",
  version_history: "Version history",
  version_history_modal_title: "Version history",
  version_history_open: "View version history",
  version_from_date: "Version from {date}",
  version_latest: "Latest",
  close: "Close",
  cancel: "Cancel",
  files_section: "Recipe files",
  no_files: "No files attached.",
  upload_file: "Upload file",
  choose_file: "Choose file",
  delete_file: "Remove file",
  delete_file_confirm: "Remove this file from the recipe?",
  delete_recipe: "Delete recipe",
  delete_recipe_confirm: "Delete this recipe? This cannot be undone.",
  toolbar_version_history: "Version history",
  toolbar_edit: "Edit",
  toolbar_images: "Add image",
  toolbar_upload_image: "Upload from computer",
  toolbar_choose_unsplash: "Choose from Unsplash",
  toolbar_delete: "Delete recipe",
  image_expand: "View full size",
  image_remove: "Remove image",
  unsplash_photo_by: "Photo by {name}",
};

export { recipes_detail_page as recipes_detail };
