export const recipes_detail_page = {
  title: "Recipe",
  short_description: "Summary",
  long_description: "Description",
  ingredients: "Ingredients",
  instructions: "Instructions",
  breadcrumb_home: "Home",
  breadcrumb_collections: "Collections",
  breadcrumb_recipes: "Recipes",
  back_to_list: "Back to recipes",
  edit_recipe: "Edit recipe",
  version_history: "Version history",
  version_history_modal_title: "Version history",
  version_history_open: "View version history",
  version_from_date: "Version from {date}",
  version_latest: "Latest",
  close: "Close",
  notes_section: "Notes",
  add_note: "Add note",
  note_body_placeholder: "How it went, what to try next…",
  save_note: "Save note",
  cancel: "Cancel",
  edit_note: "Edit",
  delete_note: "Delete",
  ever_edited: "Edited",
  associated_version: "Associated version",
  no_notes: "No notes yet.",
  link_to_version: "Link to version (optional)",
  create_note: "Add note",
  notes_for_version: "Notes for this version",
  delete_note_confirm: "Delete this note?",
  files_section: "Recipe files",
  no_files: "No files attached.",
  upload_file: "Upload file",
  choose_file: "Choose file",
  delete_file: "Remove file",
  delete_file_confirm: "Remove this file from the recipe?",
  delete_recipe: "Delete recipe",
  delete_recipe_confirm: "Delete this recipe? This cannot be undone.",
  note_files_section: "Files",
  note_no_files: "No files attached.",
  toolbar_version_history: "Version history",
  toolbar_edit: "Edit",
  toolbar_notes: "Notes",
  toolbar_images: "Add image",
  toolbar_upload_image: "Upload from computer",
  toolbar_choose_unsplash: "Choose from Unsplash",
  toolbar_delete: "Delete recipe",
  image_expand: "View full size",
  image_remove: "Remove image",
  unsplash_photo_by: "Photo by {name}",
};

export { recipes_detail_page as recipes_detail };
