# syntax=docker/dockerfile:labs
FROM node:alpine3.19

WORKDIR /app

#{ copy_packages }#
RUN npm install --omit=dev
#{ copy_src }#

WORKDIR /app/./notebook/service/notebook-service
CMD ["npm", "start"]
