/**
 * Named MDI SVG paths used by recipes SPAs and static sites.
 * Keep `mdi-*` string props working with the SVG iconset (no webfont CSS).
 * When adding a new `mdi-…` icon in a template, add the matching `@mdi/js` import here.
 * Auth / identity UI icons come from `@saflib/ory-kratos-spa/mdi-icons`.
 */
import {
  mdiAccountGroup,
  mdiAccountGroupOutline,
  mdiBookOpenPageVariantOutline,
  mdiCameraOutline,
  mdiCheckCircle,
  mdiClose,
  mdiContentSave,
  mdiDelete,
  mdiDeleteOutline,
  mdiDrag,
  mdiExclamation,
  mdiEye,
  mdiFormatListBulleted,
  mdiHistory,
  mdiImagePlus,
  mdiImageSearch,
  mdiImport,
  mdiMagnify,
  mdiMenu,
  mdiMinus,
  mdiNoteTextOutline,
  mdiPaperclip,
  mdiPencil,
  mdiPlus,
  mdiShareVariantOutline,
  mdiSilverwareForkKnife,
  mdiTimelineClock,
  mdiTuneVertical,
  mdiUpload,
  mdiViewGridOutline,
  mdiViewModule,
} from "@mdi/js";
import { kratosMdiIconPaths } from "@saflib/ory-kratos-spa/mdi-icons";

export const mdiIconPaths: Record<string, string> = {
  ...kratosMdiIconPaths,
  "mdi-account-group": mdiAccountGroup,
  "mdi-account-group-outline": mdiAccountGroupOutline,
  "mdi-book-open-page-variant-outline": mdiBookOpenPageVariantOutline,
  "mdi-camera-outline": mdiCameraOutline,
  "mdi-check-circle": mdiCheckCircle,
  "mdi-close": mdiClose,
  "mdi-content-save": mdiContentSave,
  "mdi-delete": mdiDelete,
  "mdi-delete-outline": mdiDeleteOutline,
  "mdi-drag": mdiDrag,
  "mdi-exclamation": mdiExclamation,
  "mdi-eye": mdiEye,
  "mdi-format-list-bulleted": mdiFormatListBulleted,
  "mdi-history": mdiHistory,
  "mdi-image-plus": mdiImagePlus,
  "mdi-image-search": mdiImageSearch,
  "mdi-import": mdiImport,
  "mdi-magnify": mdiMagnify,
  "mdi-menu": mdiMenu,
  "mdi-minus": mdiMinus,
  "mdi-note-text-outline": mdiNoteTextOutline,
  "mdi-paperclip": mdiPaperclip,
  "mdi-pencil": mdiPencil,
  "mdi-plus": mdiPlus,
  "mdi-share-variant-outline": mdiShareVariantOutline,
  "mdi-silverware-fork-knife": mdiSilverwareForkKnife,
  "mdi-timeline-clock": mdiTimelineClock,
  "mdi-tune-vertical": mdiTuneVertical,
  "mdi-upload": mdiUpload,
  "mdi-view-grid-outline": mdiViewGridOutline,
  "mdi-view-module": mdiViewModule,
};
