export const menus_detail = {
  breadcrumb_home: "Home",
  breadcrumb_collections: "Collections",
  breadcrumb_menus: "Menus",
  groupings_label: "Groupings",
  view_mode_menu: "Menu",
  view_mode_diner: "Diner",
  tooltip_menu_view: "Menu view",
  tooltip_diner_view: "Diner view",
  edit: "Edit",
  save: "Save",
  cancel: "Cancel",
  delete: "Delete",
  delete_confirm: "Delete this menu?",
};
