export const menus_detail = {
  breadcrumb_home: "Home",
  breadcrumb_collections: "Collections",
  breadcrumb_menus: "Menus",
  public: "Public",
  private: "Private",
  groupings_label: "Groupings",
  view_mode_menu: "Menu",
  view_mode_diner: "Diner",
  edit: "Edit",
  save: "Save",
  cancel: "Cancel",
  delete: "Delete",
  delete_confirm: "Delete this menu?",
};
