export const menu_edit_form = {
  name_label: "Menu name",
  name_placeholder: "e.g. Weeknight Dinners",
  tooltip_public: "Public",
  tooltip_private: "Private",
  groupings_label: "Sections",
  grouping_name_placeholder: "e.g. Mains, Sides, Desserts",
  add_grouping: "Add section",
  remove_grouping: "Remove section",
  remove_recipe: "Remove recipe",
  drag_handle: "Drag to reorder",
  drag_section: "Drag to reorder section",
  add_recipe_placeholder: "Add recipe…",
  submit: "Save",
  cancel: "Cancel",
};
